version: 2.1
jobs:
  setup_node:
    docker:
      - image: circleci/node:12
        environment:
          TZ: Asia/Tokyo
    steps:
      - checkout
      - run: npm ci
  setup_reviewdog:
    docker:
      - image: circleci/node:12
        environment:
          TZ: Asia/Tokyo
    steps:
      - run:
          name: install reviewdog
          command: curl --silent --fail --location https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s
  test:
    docker:
      - image: circleci/node:12
        environment:
          TZ: Asia/Tokyo
    steps:
      - checkout
      - run: npm ci
      - run: npm run textlint -- ./README.md

workflows:
  setup_and_test:
    jobs:
      # - setup_node
      - setup_reviewdog
      # - test:
      #     requires:
      #       - setup_node